server:
  port: 8005

app:
  service:
    name: Business Application The Second

# Конфигурация Эврики на стороне config сервера в файле конфигурации
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka